### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by wbyoung** [signalpillar/tox-battery#1]
I have a project that has some `pip` flags in the `requirements.txt` (specifically `--no-binary`). I'd love to use this project, but I'm getting a parser error for the file. Specifically, it seems that using `pkg_resources` doesn't support parsing that option.

**Comment by wbyoung** [comment]
I found another way around the issues I was having without the need for `tox-battery`, so I'm going to close this so it doesn't clutter up your issues. Feel free to re-open it if you want.

**Comment by signalpillar** [comment]
@wbyoung could you please share content of that `requirements.txt` file or some modified version of it. So I can try to write test against it :)

**Comment by wbyoung** [comment]
Basically it's just using `pip` options:

```
dependency_a==2.4.5
dependency_b==0.1.9 --no-binary dependency_b
dependency_c==0.23.8
```

But like I said, I found another solution, so don't work too hard to fix it on my behalf!
