### ISSUE TITLE
Migrate to tox-dev and v4 support

### ISSUE THREAD

**Issue by gaborbernat** [signalpillar/tox-battery#32]
Hello, would you consider moving the project under the tox-dev umbrella? See documentation under https://tox.readthedocs.io/en/rewrite/plugins.html#adoption-of-a-plugin-under-tox-dev-github-organization 

Furthermore, tox v4 is getting ready and we'd like to make sure this plugin is supported from day 1, we're collecting feature gaps for this under https://github.com/tox-dev/tox/issues/1974. Would be great if you could join our development chat under https://discord.gg/tox so we can assist with this. If you do so please drop in a line in the `#plugin` chat with the name of the repository you maintain. Thanks!

**Comment by The-Compiler** [comment]
> ## Features
> First experimental feature is to recreate virtual environment on requirements file update.

I thought tox 4 already does this by default, no? See https://github.com/tox-dev/tox/issues/149.

**Comment by gaborbernat** [comment]
Oh yeah.

**Comment by signalpillar** [comment]
Yeah. With tox 4 release this project will be discontinued the corresponding update of the README.
It doesn't present any value for the tox-dev community in the future, IMO.
